### PR TITLE
ADD authd service name

### PR DESCRIPTION
**Pull request by phoolish**
### Description

* ADD authd service_name attribute
* ADD authd recipe specs

### Issues Resolved

If you aren't using systemd or the name of authd service is not `ossec-authd`, allow folks to modify it.

### Check List
- [ ] All tests pass. See https://github.com/chef-brigade/sysctl/blob/master/TESTING.md
- [x] New functionality includes testing.

### CODE REVIEW

**Comment by phoolish** [comment]
In place of #93

**Comment by phoolish** [comment]
@Sliim here you go. I think this is more inline with the other recipes

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Xorima** [comment]
Hi @phoolish 

Can we get a Changelog entry and then this can be merged? 👍 

Thanks!

**Comment by damacus** [comment]
@phoolish if you can add an "unreleased" section and add your desired changelog entry to that.

That would be great.

**Comment by Xorima** [comment]
Will try to get this released tonight or tomorrow :+1:  thanks for this @phoolish

**Comment by Xorima** [comment]
and released @phoolish

**Pull request merged**
