### PR TITLE
ADD authd service_name attribute

### PR DESCRIPTION
**Pull request by phoolish**
### Description

* ADD authd service_name attribute
* ADD authd recipe specs

### Issues Resolved

If you aren't using systemd or the name of authd service is not `ossec-authd`, allow folks to modify it.

### Check List
- [ ] All tests pass. See https://github.com/chef-brigade/sysctl/blob/master/TESTING.md
- [x] New functionality includes testing.

### CODE REVIEW

**Comment by Sliim** [comment]
@phoolish I think this PR needs a cleanup.. can you create a new branch with your authd changes only and recreate the PR please? I will review it, globally I'm ok with 3 first commits. 
Thx

**Comment by pwelch** [comment]
Hey @Sliim,

How is this cleanup looking for this? I'm currently working on getting this ready for another release and was wondering if you think will be ready.

Thanks for working on this!

**Comment by phoolish** [comment]
@Sliim @pwelch I can make some time later today to work on this.

**Comment by pwelch** [comment]
@sliim,

No worries! Was just wondering if you had cycles to work on this. Thanks for taking this on!

**Pull request closed without merging**
