### PR TITLE
Green Build

### PR DESCRIPTION
**Pull request by PowerSchill**
Creates a green build and closes some issues

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by PowerSchill** [comment]
There is an actual product issue with installing ossec in Ubuntu that needs to be resolved.

**Comment by JohnRoesler** [comment]
@PowerSchill how would you like to proceed? resolve ubuntu issues here? Or merge in, make an issue and resolve it later? Do you know if the ubuntu builds passed before your PR?

**Comment by PowerSchill** [comment]
Well the purpose of the PR is to get a green build so I would like to work this PR until the issue is fixed or excluded. I don't know if the builds passed before my PR but I would venture to say no because this looks to be a package repository issue.

**Pull request merged**
